<?php

function secretpage_menu() {
	$items =  array();
	$items['secretpage'] = array(
		'title'=>'Secret Page',
		'description'=>'A secret webpage that very few people can see.',
		'page callback'=>'secretpage_do',
		'access callback' => 'user_access',
		'access arguments' => array('secret page access'),
	);
	$items['secretpage/%'] = array(
		'title'=>'Secret Page Access',
		'description'=>'Use the special code to access the secrets',
		'page callback'=>'secretpage_input',
		'page arguments'=>array(1),
		'access callback'=>TRUE,
	);
	return $items;
}

function secretpage_do() {
	$link = l(t('the access page'), 'secretpage/access');
	return t("This is a secret page that only some people have a right to see! If you want
	    to let someone else see this page, direct them to $link. Or tell them to type '/access'
	    at the end of this page's URL.");
}

function secretpage_input($var) {
    if ($var == 'access') {
	    global $user;
	    if ( $user->uid ) {
	        return t('You already have access to the Secret Page!');
        }
        else {
	        $link = l(t('register for an account'), 'user/register');
	        return t("Do you want access to secret secrets? Then $link.");
	    }
	}
	else {
	    drupal_set_message(t('Incorrect access code!'), 'error');
	    return t('Try again.');
	}
}

function secretpage_permission() {
    return array(
        'secret page access' => array(
            'title' => t('Get access to the secrets'),
            'description' => t('This is where you can access the secrets.')
        ),
    );
}
