<?php

function brine_submit_menu() {
	$items = array();
	$items['submit'] = array(
		'title'=>'Submit to Brine',
		'description'=>'Give us your jokes and we will share them with the internet.',
		'page callback'=>'brine_submit_start',
		'access callback'=>TRUE,
		);
	return $items;
}

function brine_submit_start() {
	return drupal_get_form('brine_submit_form');
}

function brine_submit_form($form_state) {
	$form = array();
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Name'),
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#required' => TRUE,
	);
	$form['type'] = array(
		'#type' => 'select',
		'#title' => t('Submission type:'),
		'#options' => array(
			0 => t('Art'),
			1 => t('Writing'),
			2 => t('Video'),
			3 => t('Audio'),
			4 => t('Pickle'),
			5 => t('Other'),
		), 
	);
	$form['title'] = array(
		'#type' => 'textfield',
		'#title' => t('Title'),
		'#description' => t('The title of your submission'),
		'#required' => TRUE,
	);
	$form['text'] = array(
		'#type' => 'textarea',
		'#title' => t('Submission'),
		'#description' => t("Put the content or idea you want to submit here. It's okay 
			if it's not complete or polished yet."),
		'#rows' => 10,
	);
	$form['file'] = array(
        '#title' => t('Attachment'),
        '#type' => 'managed_file',
        '#description' => 'If you want to submit art or if your submission is 
            format-dependent, upload the file here.',
        '#upload_location' => 'public://media/',
        '#progress_indicator' => 'throbber',
        '#prefix' => 'submitted_', 
    );
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return $form; 
}

function brine_submit_form_validate ($form, &$form_state) {
	if ( valid_email_address($form_state['values']['email']) == FALSE ) {
		form_set_error('email', t('Please enter a valid email address.'));
	}
}

function brine_submit_form_submit ($form, &$form_state) {
	
    $file = file_load($form_state['values']['file']);
    if ($file) {
        $file->status = FILE_STATUS_PERMANENT;
        file_save($file);
    }
    
	$name = check_plain($form_state['values']['name']);
	$email = check_plain($form_state['values']['email']);
	$type_raw = $form_state['values']['type'];
	if ( $type_raw == 0 ) { $type = 'Art'; }
	elseif ( $type_raw == 1 ) { $type = 'Writing'; }
	elseif ( $type_raw == 2 ) { $type = 'Audio'; }
	elseif ( $type_raw == 3 ) { $type = 'Video'; }
	elseif ( $type_raw == 4 ) { $type = 'Pickle'; }
	elseif ( $type_raw == 5 ) { $type = 'Other'; }
	$title = check_plain($form_state['values']['title']);
	$text = check_plain($form_state['values']['text']);
	
	$node = brine_submit_new_node($name, $email, $type, $title, $text, $file);
	if ($file) {
	    file_usage_add($file, 'brine_submit', 'node', $node->nid); 
	}
	drupal_set_message(t("Thanks for submitting! We'll review your stuff and get back to you ASAP."));
	drupal_goto('submit');
    
}

function brine_submit_new_node( $name, $email, $type, $title, $text, $file) {
	$node = new stdclass();
	$node->type = 'submission';
	$node->status = '0';
	$node->title = 'Submission: '.$title;
	$node->field_submitter['und'][0]['value'] = $name;
	$node->field_email_address['und'][0]['value'] = $email;
	$node->field_submission_type['und'][0]['value'] = $type;
	$node->body['und'][0]['value'] = $text;
	if ($file) {
        $node->field_attachment['und'][0]['fid'] = $file->fid;
        $node->field_attachment['und'][0]['display'] = 1;
    }
	node_save($node);
	return $node;
}